### ISSUE TITLE
[指南] 关于docker和docker compose

### ISSUE THREAD

**Issue by FeVeR-Store** [zahfiah/runda#4]
## **什么是 Docker？**

Docker 是一个开源的容器化平台，它通过将应用程序及其依赖项打包到一个轻量级的、可移植的容器中，使开发、测试和部署变得更加高效。

### **Docker 的主要特点：**
- **轻量级**：相比虚拟机，Docker 容器启动速度更快，占用资源更少。
- **一致性**：确保在开发环境和生产环境中运行的程序一致。
- **隔离性**：每个容器都是独立的，互不干扰。

因为基于docker的分发十分方便，并且可以保证在任何环境运行一致，我们就可以借助docker进行方便地开发，测试和部署。

可以解决的痛点：
 - 开发前进行的漫长而无聊的环境安装
 - 漫长而无聊的环境安装之后发现环境冲突
 - 在修复完冲突之后遇到的离奇问题，并且别人不能复现
 - 克服重重困难终于开发完毕，然后同组的人说：“兄弟，你这个跑不起来啊”

---

## **什么是 Docker Compose？**

Docker Compose 是一个工具，用于定义和管理多个 Docker 容器。它通过一个 YAML 文件（通常命名为 `docker-compose.yml`）来描述多容器的部署。

### **Docker Compose 的主要特点：**
- **简化管理**：通过一个配置文件同时启动、停止多个容器。
- **支持多服务**：特别适用于微服务架构和多容器应用。

因为docker容器是独立的，所以每次都需要一个一个启动，而且如果有互相的依赖，启动的顺序也得考量。
所以有了docker compose。

可以解决的痛点：
 - 大量docker 容器需要繁琐的启动步骤
 - 繁琐的启动意味着繁琐的关闭
 - 繁琐的启动还需要写入启动脚本，不能优雅的自动开启

---

### 1. **安装 Docker**
- 在 [[Docker 官方网站](https://www.docker.com/)](https://www.docker.com/) 下载并安装适合你操作系统的 Docker Desktop（适用于 Windows 和 macOS）。
- Linux 用户可以参考[[官方文档](https://docs.docker.com/engine/install/)](https://docs.docker.com/engine/install/)安装 Docker 引擎。

### 2. **安装 Docker Compose**
- Docker Desktop 中已自带 Docker Compose。
- Linux 用户可以通过以下命令安装：
  ```bash
  sudo apt-get update
  sudo apt-get install docker-compose
  ```

---

### 1. **启动 Docker**
确保 Docker 服务已启动。可以用以下命令检查状态：
```bash
docker --version  # 查看 Docker 版本
docker ps         # 查看运行中的容器
```

### 2. **Docker 的核心概念**
- **镜像（Image）**：一个可执行包，包含程序及其所有依赖。
- **容器（Container）**：镜像的运行实例。
- **仓库（Registry）**：存储镜像的地方，例如 Docker Hub。

### 3. **常用命令**
- 查看本地镜像：
  ```bash
  docker images
  ```
- 从 Docker Hub 拉取镜像：
  ```bash
  docker pull [镜像名]
  ```
- 创建并运行容器：
  ```bash
  docker run -d -p 8080:80 --name my_container nginx
  ```
  参数说明：
  - `-d`：后台运行。
  - `-p 8080:80`：将宿主机的 8080 端口映射到容器的 80 端口。
  - `--name my_container`：为容器指定名称。
  - `nginx`：镜像名。

- 查看运行中的容器：
  ```bash
  docker ps
  ```
- 停止容器：
  ```bash
  docker stop my_container
  ```
- 删除容器：
  ```bash
  docker rm my_container
  ```
- 删除镜像：
  ```bash
  docker rmi nginx
  ```

### 4. **Dockerfile：自定义镜像**
Dockerfile 是一个文本文件，定义了构建镜像的指令。示例：
```Dockerfile
# 使用基础镜像
FROM nginx:alpine

# 复制本地文件到容器
COPY ./index.html /usr/share/nginx/html/index.html

# 暴露端口
EXPOSE 80
```
使用以下命令构建镜像：
```bash
docker build -t my-nginx .
```
然后运行容器：
```bash
docker run -d -p 8080:80 my-nginx
```

详细的教程可以看[这篇](https://www.cnblogs.com/zhujingzhi/p/9656377.html)

---

## **基本使用：Docker Compose**

Docker Compose 主要通过 `docker-compose.yml` 文件定义多容器应用。

### 1. **docker-compose.yml 文件结构**
示例：
```yaml
version: "3.9" # Docker Compose 文件版本
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
```

详细的可以看[这篇](https://github.com/DragonV96/study-notes/blob/master/Linux%E8%BF%90%E7%BB%B4/docker/Docker-compose.yml%E6%96%87%E4%BB%B6%E5%8F%82%E6%95%B0%E8%AF%A6%E8%A7%A3.md)

### 2. **常用命令**
- 启动服务：
  ```bash
  docker-compose up
  ```
- 后台运行服务：
  ```bash
  docker-compose up -d
  ```
- 停止服务：
  ```bash
  docker-compose down
  ```
- 查看日志：
  ```bash
  docker-compose logs
  ```
- 重启服务：
  ```bash
  docker-compose restart
  ```

---

### 1. **目录结构**
```plaintext
project/
│
├── docker-compose.yml
├── html/
│   └── index.html
```

### 2. **创建文件**
- `html/index.html`：
  ```html
  <!DOCTYPE html>
  <html>
  <head>
      <title>My Docker App</title>
  </head>
  <body>
      <h1>Welcome to Docker!</h1>
  </body>
  </html>
  ```

- `docker-compose.yml`：
  ```yaml
  version: "3.9"
  services:
    web:
      image: nginx:alpine
      ports:
        - "8080:80"
      volumes:
        - ./html:/usr/share/nginx/html
  ```

### 3. **运行应用**
- 在项目目录中运行：
  ```bash
  docker-compose up
  ```
- 打开浏览器访问 `http://localhost:8080`，即可看到网页内容。
